on:
  push:

env:
  tf_working_dir: './env/dev'

jobs:
  check:
    name: githubaction check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: ./tf.sh install
    
#      - name: Terraform install
#        uses: darzanebor/github-terraform-wrapper@v0.0.2c
#        with:
#          tf_command: 'install'
